# Generated by Django 5.2.1 on 2025-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('buah', 'Buah'), ('sayur', 'Sayur'), ('groceries', 'Groceries'), ('meat', 'Meat'), ('other', 'Other')], max_length=50),
        ),
    ]
